/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.deliveryservice;

import com.deliveryservice.config.AppConfig;
import com.deliveryservice.services.analytics.AnalyticsService;
import com.deliveryservice.services.analytics.AverageStatistics;
import com.deliveryservice.services.analytics.DefaultAnalyticsService;
import com.deliveryservice.services.couriers.CouriersService;
import com.deliveryservice.services.couriers.DefaultCouriersService;
import com.deliveryservice.services.delivery.DefaultDeliveryService;
import com.deliveryservice.services.delivery.DeliveryService;
import com.deliveryservice.services.kitchen.DefaultKitchenService;
import com.deliveryservice.services.kitchen.KitchenService;
import com.deliveryservice.services.orders.DefaultOrdersService;
import com.deliveryservice.services.orders.OrdersService;
import com.deliveryservice.strategies.Strategy;
import com.deliveryservice.strategies.StrategyFactory;

public class App {
    public static void main(String[] args) {
        OrdersService orderService = new DefaultOrdersService();
        KitchenService kitchenService = new DefaultKitchenService();
        CouriersService couriersService = new DefaultCouriersService();
        Strategy strategy = StrategyFactory.getStrategy(AppConfig.getInstance().getStrategy());
        AnalyticsService analyticsService = new DefaultAnalyticsService(
            new AverageStatistics(),
            new AverageStatistics()
        );

        DeliveryService deliveryService = new DefaultDeliveryService(
            kitchenService,
            orderService,
            couriersService,
            strategy,
            analyticsService
        );

        deliveryService.startProcessingOrders();
    }
}
